config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'
  resources :messages, only: [:index, :show]
  get 'coke', to: 'messages#coke'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :external_created_at,
           :user_followers,
           :user_id,
           :message,
           :sentiment,
           :user_handle
  validates_uniqueness_of :message, scope: [:user_handle, :external_created_at]

  def self.coke_messages
    self.where("message ILIKE ANY(ARRAY['%coke%', '%coca-cola%', '%diet-cola%'])")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    fetch_success = MessageFetcher.messages!
    flash[:danger] = 'Something went wrong while getting new messages!' if !fetch_success
    @messages = Message.all
  end

  def coke
    fetch_success = MessageFetcher.messages!
    flash[:danger] = 'Something went wrong while getting new messages!' if !fetch_success
    @messages = Message.coke_messages.order(sentiment: :desc)
    @percentage_coke = (@messages.count/Message.count.to_d) * 100
    render :index
  end

  def show
    @message = Message.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash">
      <% flash.each do |klass, msg| %>
      <div class="alert alert-<%= klass %>">
        <%= msg %>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1>All Messages</h1>
<h2> <%= "#{@percentage_coke.round(2)}% of messages have coke mentioned" if @percentage_coke %> </h2>
<table class="table">
  <thead>
    <tr>
      <th>Handle</th>
      <th>Message</th>
      <th>Sentiment</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |m| %>
      <tr class="message">
        <th><%= m.user_handle %></th>
        <td><%= link_to m.message, message_path(m) %></td>
        <td><%= m.sentiment %></td>
      </tr>
    <% end if @messages %>
  </tbody>
</table>

app/views/messages/show.html.erb
Message: <%= @message.message %><br>
Sentiment: <%= @message.sentiment %><br>
Followers: <%= @message.user_followers %><br>
Handle: <%= @message.user_handle %><br>